FROM golang:1.24.1-alpine

# Declare ARGs for all environment variables that the platform should provide
ARG ADDR
ARG EXTERNAL_URL
ARG FRONTEND_URL
ARG ENV
ARG TIMEZONE
ARG DB_HOST
ARG DB_PORT
ARG DB_USER
ARG DB_PASSWORD
ARG DB_NAME
ARG DB_MAX_OPEN_CONNS
ARG DB_MAX_IDLE_CONNS
ARG DB_MAX_IDLE_TIME
ARG R2_ENDPOINT
ARG R2_ACCESS_KEY_ID
ARG R2_SECRET_ACCESS_KEY
ARG R2_BUCKET_NAME
ARG R2_REGION
ARG R2_PUBLIC_URL
ARG R2_ENABLED
ARG MAIL_HOST
ARG MAIL_PORT
ARG MAIL_USERNAME
ARG MAIL_PASSWORD
ARG MAIL_ENCRYPTION
ARG MAIL_FROM_ADDRESS
ARG MAIL_FROM_NAME
ARG SLACK_WEBHOOK_URL
ARG SLACK_CHANNEL
ARG SLACK_USERNAME
ARG SLACK_ICON_EMOJI
ARG SLACK_ENABLED
ARG BASIC_AUTH_USERNAME
ARG BASIC_AUTH_PASSWORD
ARG TOKEN_SECRET
ARG TOKEN_AUDIENCE
ARG TOKEN_ISSUER
ARG REDIS_ADDR
ARG REDIS_PASSWORD
ARG REDIS_DB
ARG REDIS_ENABLED
ARG RATE_LIMITER_ENABLED
ARG RATE_LIMITER_REQUEST_COUNT

# Convert ARGs to ENV variables without revealing defaults
ENV ADDR=${ADDR}
ENV EXTERNAL_URL=${EXTERNAL_URL}
ENV FRONTEND_URL=${FRONTEND_URL}
ENV ENV=${ENV}
ENV TIMEZONE=${TIMEZONE}
ENV DB_HOST=${DB_HOST}
ENV DB_PORT=${DB_PORT}
ENV DB_USER=${DB_USER}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV DB_NAME=${DB_NAME}
ENV DB_MAX_OPEN_CONNS=${DB_MAX_OPEN_CONNS}
ENV DB_MAX_IDLE_CONNS=${DB_MAX_IDLE_CONNS}
ENV DB_MAX_IDLE_TIME=${DB_MAX_IDLE_TIME}
ENV R2_ENDPOINT=${R2_ENDPOINT}
ENV R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
ENV R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
ENV R2_BUCKET_NAME=${R2_BUCKET_NAME}
ENV R2_REGION=${R2_REGION}
ENV R2_PUBLIC_URL=${R2_PUBLIC_URL}
ENV R2_ENABLED=${R2_ENABLED}
ENV MAIL_HOST=${MAIL_HOST}
ENV MAIL_PORT=${MAIL_PORT}
ENV MAIL_USERNAME=${MAIL_USERNAME}
ENV MAIL_PASSWORD=${MAIL_PASSWORD}
ENV MAIL_ENCRYPTION=${MAIL_ENCRYPTION}
ENV MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
ENV MAIL_FROM_NAME=${MAIL_FROM_NAME}
ENV SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
ENV SLACK_CHANNEL=${SLACK_CHANNEL}
ENV SLACK_USERNAME=${SLACK_USERNAME}
ENV SLACK_ICON_EMOJI=${SLACK_ICON_EMOJI}
ENV SLACK_ENABLED=${SLACK_ENABLED}
ENV BASIC_AUTH_USERNAME=${BASIC_AUTH_USERNAME}
ENV BASIC_AUTH_PASSWORD=${BASIC_AUTH_PASSWORD}
ENV TOKEN_SECRET=${TOKEN_SECRET}
ENV TOKEN_AUDIENCE=${TOKEN_AUDIENCE}
ENV TOKEN_ISSUER=${TOKEN_ISSUER}
ENV REDIS_ADDR=${REDIS_ADDR}
ENV REDIS_PASSWORD=${REDIS_PASSWORD}
ENV REDIS_DB=${REDIS_DB}
ENV REDIS_ENABLED=${REDIS_ENABLED}
ENV RATE_LIMITER_ENABLED=${RATE_LIMITER_ENABLED}
ENV RATE_LIMITER_REQUEST_COUNT=${RATE_LIMITER_REQUEST_COUNT}

# Install Go build tools, make, migration tools, and other common packages
RUN apk add --no-cache \
    make \
    bash \
    gcc \
    musl-dev \
    tzdata \
    curl \
    git \
    sqlite \
    mysql-client \
    mariadb-connector-c-dev \
    ca-certificates

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o bin/main ./cmd/api/*.go

RUN go install -tags 'mysql' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

ENV PATH="/go/bin:$PATH"

COPY .env /app/.env

EXPOSE 8080

CMD ["/app/bin/main"]
